# Generated by Django 2.2.3 on 2020-03-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.CharField(max_length=100, null=True, verbose_name='price of product')),
                ('product_category', models.CharField(max_length=100, null=True, verbose_name='list of Catergories')),
                ('product_name', models.ImageField(null=True, upload_to='', verbose_name='product name')),
                ('product_desc', models.ImageField(null=True, upload_to='', verbose_name='product description')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='email')),
                ('wallet', models.CharField(max_length=8, null=True, verbose_name='wallet')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='phone number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orders', models.CharField(max_length=100, null=True, verbose_name='orders')),
                ('pending', models.CharField(max_length=100, verbose_name='pending orders')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_id', to='shop.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_price', models.CharField(max_length=100, null=True, verbose_name='price of product')),
                ('product_name', models.ImageField(null=True, upload_to='', verbose_name='product name')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_id', to='shop.UserProfile')),
            ],
        ),
    ]
