# Generated by Django 2.2.3 on 2020-04-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200405_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='price of product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='price of product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='wallet'),
        ),
    ]
