# Generated by Django 2.2.3 on 2020-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200413_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.CharField(max_length=1000, null=True, verbose_name='Cart Item'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='price of product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='wallet'),
        ),
    ]
