# Generated by Django 2.2.3 on 2020-06-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vtu_transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=100, null=True, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='amout')),
                ('ref_id', models.CharField(max_length=100, verbose_name='reference number s')),
                ('phone', models.CharField(max_length=100, verbose_name='phone number credited')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vtu_id', to='shop.UserProfile')),
            ],
        ),
    ]
